package:
  name: libruntime
  version: "1.0.0"
    
build:
  number: 0
  track_features:
    - vc12                  [win]
    
about:
  home: http://statiskit.rtfd.io/
  license: Apache License 2.0
  summary: Collection of utilities for using compiled libraries.
  
requirements:
  build:
    - vs2013_runtime      [win]
  run:
    - vs2013_runtime      [win]
