package:
  name: libtoolchain
  version: "1.0.0"
    
build:
  number: 0
  track_features:
    - vc14                 [win]

about:
  home: http://statiskit.rtfd.io/
  license: Apache License 2.0
  summary: Collection of utilities for compiling libraries.
  
requirements:
  build:
    - python
    - scons-tools
    - gcc_linux-64        [linux]
    - gxx_linux-64        [linux]
    - gfortran_linux-64   [linux]
    - clang_osx-64        [osx]
    - clangxx_osx-64      [osx]
    - gfortran_osx-64     [osx]
    - pywin32             [win]
    - vs2015_runtime      [win]
  run:
    - python
    - scons-tools
    - gcc_linux-64        [linux]
    - gxx_linux-64        [linux]
    - clang_osx-64        [osx]
    - clangxx_osx-64      [osx]
    - pywin32             [win]
    - vs2015_runtime      [win]
