package:
    name: statiskit-unstable
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    track_features:
        - unstable
about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package forcing the installation of StatisKit unstable packages 