package:
  name: libboost
  version: 1.61.0

source:
  fn:  boost_1_61_0.tar.bz2
  url: http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2

build:
  number: 0

about:
  home: http://www.boost.org/
  license: Boost-1.0

requirements:
  build:
    - python 2.7*
    - libdev
    - python
    - icu 58.*          [unix]
    - bzip2             [unix]
    - zlib
  run:
    - python 2.7*
    - icu 58.*          [unix]
    - zlib
    - librun