about:
  brief: Python plugin system
  name: PluginTools
  version: 0.1.0
authors:
  basename: AUTHORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
coveralls:
  account: StatisKit
  host: github
  project: PluginTools
landscape:
  account: StatisKit
  host: github
  project: PluginTools
license:
  basename: LICENSE.rst
  plugin: CeCILL-C
  width: 78
readthedocs:
  project: PluginTools
rst:
  plugin: default
  target:
  - README.rst
  - doc/index.rst
travis:
  account: StatisKit
  project: PluginTools
version:
  plugin: semantic
