about:
  authors:
  - !!python/unicode 'Pierre Fernique'
  brief: !!python/unicode 'Tool kit for Python packages'
  email: !!python/unicode 'statiskit@googlegroups.com'
  name: !!python/unicode 'PkgTk'
  plugin: github
  homepage: 'pkgtk.readthedocs.io'
authors:
  basename: CONTRIBUTORS.rst
  format: '* `{name} <{email}>`_ ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  exclude:
  - ./.git/*
  - ./build/*
  plugin: CeCILL-C
  width: 78
