about:
  brief: Toolkit for packaging
  homepage: pkgtk.readthedocs.io
  name: PkgTk
  plugin: github
authors:
  basename: CONTRIBUTORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
license:
  basename: LICENSE.rst
  exclude:
  - ./.git/*
  - ./build/*
  plugin: CeCILL-C
  width: 78
