about:
  brief: 'Toolkit for packaging'
  homepage: ''
  name: 'PkgTk'
  plugin: github
authors:
  basename: CONTRIBUTORS.rst
  format: '* {name} <{email}> ({score})'
  plugin: commit
license:
  plugin: CeCILL-C
  exclude:
    - "./.git/*"
    - "./build/*"