language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env:
        - TRAVIS_DOCKER="false"
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - TRAVIS_DOCKER="true"
    - os: osx
      osx_image: xcode7.2
      env:
        - TRAVIS_DOCKER="false"
        
before_install:
    - if [[ "$TRAVIS_DOCKER" = "false" ]] && [[ "$TRAVIS_OS_NAME" = "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_DOCKER" = "false" ]] && [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
        curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o miniconda.sh;
      fi
    - [[ "$TRAVIS_DOCKER" = "true" ]] || bash miniconda.sh -b -p $HOME/miniconda
    - [[ "$TRAVIS_DOCKER" = "true" ]] || export PATH=$HOME/miniconda/bin:$PATH
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda config --set always_yes yes --set changeps1 no
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda update -q conda
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda info -a
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda install conda-build

install:
    - [[ "$TRAVIS_DOCKER" = "true" ]] || pip install python-coveralls
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda build toolchain
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda create -n _travis toolchain --use-local
    - [[ "$TRAVIS_DOCKER" = "true" ]] || source activate _travis

script:
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda build libboost-python -c statiskit
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda build python-scons -c statiskit
    - [[ "$TRAVIS_DOCKER" = "true" ]] || conda build python-parse -c statiskit

after_success:
    - [[ "$TRAVIS_DOCKER" = "true" ]] || coveralls
    - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ "$TRAVIS_DOCKER" = "false" ]] && [[ ! -z $ANACONDA_USERNAME ]] && [[ ! -z $ANACONDA_PASSWORD ]]; then
        conda install anaconda-client;
        anaconda login --username "$ANACONDA_USERNAME" --password "$ANACONDA_PASSWORD";
        for CONDA_RECIPE in toolchain libboost-python python-scons python-parse; do
          CONDA_FILE=`conda build $CONDA_RECIPE --output`; 
          anaconda upload --user statiskit ${CONDA_FILE%%} --force;
        done;
      fi
    - if [[ "$TRAVIS_BRANCH" = "master" ]] && [[ "$TRAVIS_PULL_REQUEST" = "false" ]] && [[ "$TRAVIS_OS_NAME" = "linux" ]] && [[ "$TRAVIS_DOCKER" = "true" ]] && [[ ! -z $DOCKER_USERNAME ]] && [[ ! -z $DOCKER_PASSWORD ]]; then
        docker build --quiet --build-arg BUILD="false" -t statiskit/ubuntu . ;
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
        docker push statiskit/ubuntu;
      fi
