platform:
  - x64

environment:
  matrix:
    - MINICONDA: "3"
    - MINICONDA: "2"

install:
  - git clone https://gist.github.com/a08b6eb1c97fad864de50601d70008c8.git config-appveyor
  - cd config-appveyor
  - call config.bat
  - cd ..
  
build_script:
  - set ANACONDA_FLAGS="--no-test"
  - cd conda
  - '%CMD_IN_ENV% call bld.bat'
  - cd ..
  - set ANACONDA_FLAGS=""

  
on_success:
  - del test/test_about.py
  - cd conda
  - call install.bat
  - cd ..
  - call pkgtk authors
  - cd conda
  - set BUILD_TARGETS=python-pkgtk
  - '%CMD_IN_ENV% call bld.bat'
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if not "%ANACONDA_USERNAME%"=="" if not "%ANACONDA_PASSWORD%"=="" call upload.bat
  - cd ..
