environment:
  CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"
  matrix:
    - TARGET_ARCH: x64
      PYTHON_VERSION: "2.7"
      CONDA_PY: 27
    #- PLATFORM: x86
    #  PYTHON_VERSION: "2.7"
      
install:
  - 'if "%TARGET_ARCH%" == "x86" set PATH=C:\Miniconda;C:\Miniconda\Scripts;%PATH%'
  - 'if "%TARGET_ARCH%" == "x64" set PATH=C:\Miniconda-x64;C:\Miniconda-x64\Scripts;%PATH%'
  - 'git clone https://github.com/pelson/Obvious-CI.git'
  - 'move /y ".\Obvious-CI\scripts\obvci_appveyor_python_build_env.cmd" ".\conda\obvci_appveyor_python_build_env.cmd"' 
  #- 'set DISTUTILS_USE_SDK=1'
  #- 'set MSSdk=1'
  #- 'set WIN_SDK_ROOT="C:\Program Files\Microsoft SDKs\Windows"'
  #- 'set WINDOWS_SDK_VERSION="v7.0"'
  #- 'echo %WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%'
  #- 'dir %WIN_SDK_ROOT%\%WINDOWS_SDK_VERSION%' 
  #- 'if "%PLATFORM%" == "x64" appveyor DownloadFile "https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py"'
  #- 'if "%PLATFORM%" == "x64" python bootstrap-obvious-ci-and-miniconda.py =C:\Conda %PLATFORM% %CONDA_PY:~0,1% --without-obvci'
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda update -q conda"
  - "conda info -a"
  - "conda install conda-build=1.21"

build_script:
  - cd conda
  - echo echo ON >> tmp.bat
  - more +7 "bld.bat" >> tmp.bat
  - powershell -Command "(gc tmp.bat) -replace 'conda build', '%CMD_IN_ENV% conda build' | Out-File tmp.bat"
  - del bld.bat
  - more tmp.bat >> bld.bat
  - "call bld.bat"
  - cd ..
  
on_success:
  - cd conda
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if not "%ANACONDA_USERNAME%"=="" if not "%ANACONDA_PASSWORD%"=="" call upload.bat
  - cd ..
