platform:
  - x64

install:
  - git clone https://gist.github.com/a08b6eb1c97fad864de50601d70008c8.git config-appveyor
  - cd config-appveyor
  - call config.bat
  - cd ..
  
build_script:
  - cd conda
  - echo echo ON >> tmp.bat
  - powershell -Command "(gc bld.bat) -replace 'build', 'build --no-test' | Out-File bld.bat"
  - more +8 "bld.bat" >> tmp.bat
  - del bld.bat
  - more tmp.bat >> bld.bat
  - '%CMD_IN_ENV% call bld.bat'
  - cd ..
  
on_success:
  - cd conda
  - call install.bat
  - cd ..
  - call pkgtk authors
  - cd conda
  - powershell -Command "(gc bld.bat) -replace 'build --no-test', 'build' | Out-File bld.bat"
  - more bld.bat >> tmp.bat
  - del bld.bat
  - more tmp.bat >> bld.bat
  - set BUILD_TARGETS=python-pkgtk
  - '%CMD_IN_ENV% call bld.bat'
  - if "%APPVEYOR_REPO_BRANCH%"=="master" if not "%ANACONDA_USERNAME%"=="" if not "%ANACONDA_PASSWORD%"=="" call upload.bat
  - cd ..