package:
  name: boost-suite
  version: 1.68.0

source:
  fn: boost_1_67_0.tar.bz2
  sha256: 2684c972994ee57fc5632e03bf044746f6eb45d4920c343937a465fd67a5adba
  url: https://dl.bintray.com/boostorg/release/1.67.0/source/boost_1_67_0.tar.bz2

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - libtoolchain
  host:
    - python
    - icu               [unix]
    - bzip2             [unix]
    - libiconv          [osx]
    - xz
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries.

test:
  requires:
    - libtoolchain
    - python

outputs:
  - name: libboost-dev            
    script: libboost-dev.sh   
    requirements:                 
      build:                      
        - libtoolchain
      host:
        - icu               [unix]
        - bzip2             [unix]
        - libiconv          [osx]
        - xz
        - zlib            
  - name: libboost                
    script: libboost.sh           
    requirements:                 
      build:                      
        - libtoolchain
      host:
        - icu               [unix]
        - bzip2             [unix]
        - libiconv          [osx]
        - xz
        - zlib            
  - name: libboost_python
    script: libboost_python.sh
    requirements:
      build:
        - libtoolchain
      host:
        - python
        - icu               [unix]
        - bzip2             [unix]
        - libiconv          [osx]
        - xz
        - zlib
      run:
        - python
        - {{ pin_subpackage("libboost", exact=True) }}
