package:
  name: boost-suite
  version: 1.68.0

source:
  fn: boost_1_68_0.tar.bz2
  sha256: 7f6130bc3cf65f56a618888ce9d5ea704fa10b462be126ad053e80e553d6d8b7
  url: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2

build:
  number: 0

requirements:
  build:
    - python
    - libtoolchain
    - python
    - icu 58.*          [unix]
    - bzip2             [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries.

test:
  requires:
    - libtoolchain
    - python

outputs:
  - name: libboost-dev            [not py2k]
    script: libboost_dev.py       [not py2k]
    requirements:                 [not py2k]
      build:                      [not py2k]
        - path.py                 [not py2k]
        - libtoolchain            [not py2k]
        - icu 58.*                [linux and not py2k]
  - name: libboost                [not py2k]
    script: libboost.py           [not py2k]
    requirements:                 [not py2k]
      build:                      [not py2k]
        - path.py                 [not py2k]
        - libtoolchain            [not py2k]
        - icu 58.*                [linux and not py2k]
      run:                        [not py2k]
        - icu 58.*                [linux and not py2k]
  - name: libboost_python
    script: libboost_python.py
    requirements:
      build:
        - path.py
        - icu 58.*                [linux]
        - libtoolchain
      run:
        - python
        - {{ pin_subpackage("libboost", exact=True) }}
