package:
  name: python-dev
  version: "1.0.0"
    
build:
  number: 0

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL

requirements:
  build:
    - libdev
    - python
    - setuptools
    - python-scons
    - path.py
    - pywin32                      [win]
    - pyyaml
    - nose
    - coverage
  run:
    - libdev
    - python
    - setuptools
    - python-scons
    - path.py
    - pywin32                      [win]
    - pyyaml
    - nose
    - coverage