package:
    name: libstatiskit
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    features:
        - {{ environ.get('CONDA_FEATURE', 'stable') }}
    track_features:
        - {{ environ.get('CONDA_FEATURE', 'stable') }}

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package containing the C++ definitions to the StatisKit software suite

requirements:
    build:
        - python
        - libstatiskit_stl
        - libstatiskit_linalg
        - libstatiskit_core
        - libstatiskit_glm
    run:
        - python
        - {{ pin_compatible('libstatiskit_stl', exact=True) }}
        - {{ pin_compatible('libstatiskit_linalg', exact=True) }}
        - {{ pin_compatible('libstatiskit_core', exact=True) }}
        - {{ pin_compatible('libstatiskit_glm', exact=True) }}