package:
    name: libstatiskit
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package containing the C++ definitions to the StatisKit software suite

requirements:
    build:
        - libstatiskit_stl
    run:
        - {{ pin_compatible('libstatiskit_stl', exact=True) }}