package:
  name: vcs
  version: "1.0.0"
    
build:
  number: 0
  always_include_files:
    - etc/gitconfig

about:
  home: http://statiskit.readthedocs.io
  license: Apache License 2.0
  summary: A collection of utilities for version control.

requirements:
  build:
    - gitflow
  run:
    - gitflow