package:
  name: python-toolchain
  version: "1.0.0"
    
build:
  number: 0

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL

requirements:
  build:
    - python
    - setuptools
    - scons-tools
    - path.py
    - pywin32                      [win]
    - pyyaml
    - nose
    - coverage
    - sphinx
    - cmake
    - pillow
  run:
    - python
    - setuptools
    - scons-tools
    - path.py
    - pywin32                      [win]
    - pyyaml
    - nose
    - coverage
    - sphinx
    - pillow