package:
  name: statiskit-dev
  version: "1.0.0"

build:
  number: 0

about:
  home: http://statiskit.readthedocs.io/
  license: Apache License 2.0

requirements:
  build:
    - python
    - libboost
    - libboost_core-dev
    - libtoolchain
    - python-autowig
    - python-clanglite
    - python-clang                                   [win]
    - python-toolchain
    - vcs
    - devops-tools
  run:
    - python
    - {{ pin_compatible('libboost', exact=True) }}
    - {{ pin_compatible('libboost_core-dev', exact=True) }}
    - {{ pin_compatible('libtoolchain', exact=True) }}
    - {{ pin_compatible('python-toolchain', exact=True) }}
    - {{ pin_compatible('python-autowig', exact=True) }}
    - {{ pin_compatible('python-clanglite', exact=True) }}
    - {{ pin_compatible('python-clang', exact=True) }}      [win]
    - {{ pin_compatible('vcs', exact=True) }}
    - {{ pin_compatible('devops-tools', exact=True) }}

