package:
  name: gmp
  version: 6.1.0

source:
  fn: gmp-6.1.0.tar.bz2
  url: ftp://ftp.gnu.org/gnu/gmp/gmp-6.1.0.tar.bz2

build:
  number: 3
  detect_binary_files_with_prefix: True

about:
  home: http://gmplib.org/
  license: GPL 3

test:
  files:
    - test.c