
# Adpated from https://github.com/conda/conda-recipes/tree/master/boost
package:
  name: libboost-python
  version: 1.61.0

source:
  fn: boost_1_61_0.tar.bz2 # [not win]
  url: http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2 # [not win]
  fn: boost_1_61_0.zip # [win]
  url: https://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.zip # [win]

build:
  number: 0
  script_env:
    - TOOLCHAIN # [not win]
  features:
    - {{ TOOLCHAIN }} # [not win]
  track_features:
    - {{ TOOLCHAIN }} # [not win]

about:
  home: http://www.boost.org/
  license: Boost-1.0

requirements:
  build:
    - toolchain
    - python
  run:
    - python
