
package:
  name: boost-meta
  version: 1.61.0

# source:
#   git_url: https://github.com/boostorg/boost.git
#   git_tag: boost-1.61.0

build:
  number: 0
  features:
    - vc12                [win]
  track_features:
    - vc12                [win]

requirements:
  build:
    - python
    - libtoolchain
    - icu 58.*             [unix]
    - bzip2                [unix]
    - zlib
    - libboost_core-dev
    - libboost
    
about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries.

outputs:
  - name: libboost_iostreams-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_iostreams
  - name: libboost_math-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_math
  - name: libboost_program_options-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_program_options
  - name: libboost_context-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_context
  - name: libboost_test-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_test
  - name: libboost_type_erasure-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_type_erasure
  - name: libboost_date_time-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_date_time
  - name: libboost_atomic-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_atomic
  - name: libboost_regex-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_regex
  - name: libboost_locale-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_locale
  - name: libboost_signals-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_signals
  - name: libboost_system-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_system
  - name: libboost_thread-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_thread
  - name: libboost_chrono-dev
    requirements:
      run:
        - libboost_stopwatches-dev
        - libboost_core-dev
        - libboost_chrono
  - name: libboost_wave-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_wave
  - name: libboost_python-dev
    requirements:
      build:
        - python
      run:
        - libboost_core-dev
        - libboost_python
        - python
  - name: libboost_random-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_random
  - name: libboost_graph-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_graph
  - name: libboost_serialization-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_serialization
  - name: libboost_timer-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_timer
  - name: libboost_coroutine-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_coroutine
  - name: libboost_log-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_log
  - name: libboost_container-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_container
  - name: libboost_filesystem-dev
    requirements:
      run:
        - libboost_core-dev
        - libboost_filesystem