
package:
  name: boost-meta
  version: 1.61.0

source:
  git_url: https://github.com/boostorg/boost.git
  git_tag: boost-1.61.0

build:
  number: 0
  features:
    - vc12                [win]
  track_features:
    - vc12                [win]

requirements:
  build:
    - python
    - libtoolchain
    - icu 58.*             [unix]
    - bzip2                [unix]
    - zlib

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries.

outputs:
  - name: libboost_iostreams-dev
    run_exports:
        - {{ pin_subpackage("libboost_iostreams", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_iostreams", exact=True) }}
  - name: libboost_math-dev
    run_exports:
        - {{ pin_subpackage("libboost_math", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_math", exact=True) }}
  - name: libboost_program_options-dev
    run_exports:
        - {{ pin_subpackage("libboost_program_options", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_program_options", exact=True) }}
  - name: libboost_context-dev
    run_exports:
        - {{ pin_subpackage("libboost_context", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_context", exact=True) }}
  - name: libboost_test-dev
    run_exports:
        - {{ pin_subpackage("libboost_test", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_test", exact=True) }}
  - name: libboost_type_erasure-dev
    run_exports:
        - {{ pin_subpackage("libboost_type_erasure", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_type_erasure", exact=True) }}
  - name: libboost_date_time-dev
    run_exports:
        - {{ pin_subpackage("libboost_date_time", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_date_time", exact=True) }}
  - name: libboost_atomic-dev
    run_exports:
        - {{ pin_subpackage("libboost_atomic", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_atomic", exact=True) }}
  - name: libboost_regex-dev
    run_exports:
        - {{ pin_subpackage("libboost_regex", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_regex", exact=True) }}
  - name: libboost_locale-dev
    run_exports:
        - {{ pin_subpackage("libboost_locale", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_locale", exact=True) }}
  - name: libboost_signals-dev
    run_exports:
        - {{ pin_subpackage("libboost_signals", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_signals", exact=True) }}
  - name: libboost_system-dev
    run_exports:
        - {{ pin_subpackage("libboost_system", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_system", exact=True) }}
  - name: libboost_thread-dev
    run_exports:
        - {{ pin_subpackage("libboost_thread", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_thread", exact=True) }}
  - name: libboost_chrono-dev
    run_exports:
        - {{ pin_subpackage("libboost_chrono", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_stopwatches-dev", exact=True) }}
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_chrono", exact=True) }}
  - name: libboost_wave-dev
    run_exports:
        - {{ pin_subpackage("libboost_wave", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_wave", exact=True) }}
  - name: libboost_python-dev
    run_exports:
        - {{ pin_subpackage("libboost_python", exact=True) }}
    requirements:
      build:
        - python
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_python", exact=True) }}
        - python
  - name: libboost_random-dev
    run_exports:
        - {{ pin_subpackage("libboost_random", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_random", exact=True) }}
  - name: libboost_graph-dev
    run_exports:
        - {{ pin_subpackage("libboost_graph", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_graph", exact=True) }}
  - name: libboost_serialization-dev
    run_exports:
        - {{ pin_subpackage("libboost_serialization", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_serialization", exact=True) }}
  - name: libboost_timer-dev
    run_exports:
        - {{ pin_subpackage("libboost_timer", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_timer", exact=True) }}
  - name: libboost_coroutine-dev
    run_exports:
        - {{ pin_subpackage("libboost_coroutine", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_coroutine", exact=True) }}
  - name: libboost_log-dev
    run_exports:
        - {{ pin_subpackage("libboost_log", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_log", exact=True) }}
  - name: libboost_container-dev
    run_exports:
        - {{ pin_subpackage("libboost_container", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_container", exact=True) }}
  - name: libboost_filesystem-dev
    run_exports:
        - {{ pin_subpackage("libboost_filesystem", exact=True) }}
    requirements:
      run:
        - {{ pin_subpackage("libboost_core-dev", exact=True) }}
        - {{ pin_subpackage("libboost_filesystem", exact=True) }}