package:
  name: pybind11-suite
  version: 2.2.4

source:
  fn: v2.2.4.tar.gz
  sha256: b69e83658513215b8d1443544d0549b7d231b9f201f6fc787a2b2218b408181e
  url: https://github.com/pybind/pybind11/archive/v2.2.4.tar.gz

build:
  number: 0

requirements:
  build:
    - libtoolchain
    - cmake
  host:
    - python
    - setuptools

about:
  home: https://pybind11.readthedocs.io
  license: BSD 3-Clause
  summary: Seamless operability between C++11 and Python

test:
  requires:
    - libtoolchain
    - python

outputs:
  - name: libpybind11-dev            
    script: libpybind11-dev.sh   [unix]
    script: libpybind11-dev.bat  [win]
    requirements:                 
      build:                      
        - libtoolchain
        - cmake
      host:
        - python          
        - setuptools
  - name: python-pybind11                
    script: python-pybind11.sh     [unix]      
    script: python-pybind11.bat    [win]      
    requirements:                 
      build:                      
        - libtoolchain
        - cmake
      host:
        - python
        - setuptools
      run:
        - python