package:
  name: statiskit-toolchain
  version: 1.0.0


build:
  number: 0

about:
  home: http://statiskit.rtfd.io/
  license: Apache License 2.0
  summary: Collection of utilities for developing the StatisKit software suite.
  
requirements:
  build:
    - python
  run:
    - vcs
    - libtoolchain
    - python-toolchain
    - libboost
    - python-autowig
    - python-clanglite
    - python