package:
  name: gitflow
  version: 0.4.1

source:
  git_tag: 0.4.1
  git_url: git@github.com:nvie/gitflow.git

build:
  number: 0

requirements:
  build: 
    - git
    - cmake
  run:
    - git

about:
  home: https://github.com/nvie/gitflow
  license: Copyright 2010 Vincent Driessen.
  summary: A collection of Git extensions to provide high-level repository operations for Vincent Driessen's branching model.