package:
  name: openssl
  version: 1.0.2h

source:
  fn: openssl-1.0.2h.tar.gz
  url: http://www.openssl.org/source/openssl-1.0.2h.tar.gz
  sha256: 1d4007e53aad94a5b2002fe045ee7bb0b3d98f1a47f8b2bc851dcd1c74332919

build:
  detect_binary_files_with_prefix: True
  features:
    - vc9     [win and py27]
    - vc10    [win and py34]
    - vc14    [win and py35]

requirements:
  build:
    - nasm    [win32]
    - perl    [win]
    - gcc
    - glibc

about:
  home: http://www.openssl.org/
  license: Apache-style (http://www.openssl.org/source/license.html)
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols