package:
  name: python-dbg
  version: "1.0.0"
    
build:
  number: 0

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL

requirements:
  build:
    - python
    - nose
    - coverage
    - python-scons
  run:
    - python
    - nose
    - coverage
