package:
  name: libboost_python
  version: 1.68.0

source:
  fn: boost_1_68_0.tar.bz2
  sha256: 7f6130bc3cf65f56a618888ce9d5ea704fa10b462be126ad053e80e553d6d8b7
  url: https://dl.bintray.com/boostorg/release/1.68.0/source/boost_1_68_0.tar.bz2

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libboost-dev
    - libboost
    - python
    - libtoolchain
    - icu               [unix]
    - bzip2             [unix]
    - libiconv          [osx]
    - xz
    - zlib
  run:
    - python

about:
  home: http://www.boost.org/
  license: Boost-1.0
  summary: Boost provides free peer-reviewed portable C++ source libraries.