package:
    name: statiskit
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  features:
    - {{ environ.get('CONDA_FEATURE', 'stable') }}
  track_features:
    - {{ environ.get('CONDA_FEATURE', 'stable') }}

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package containing all interfaces to the StatisKit software suite and necessary toolchains

requirements:
  build:
    - python
    - statiskit-{{ environ.get('CONDA_FEATURE', 'stable') }}
    - devops-tools
    - vcs
    - statiskit-tools
    - libtoolchain-dev
    - libstatiskit-dev
    - libtoolchain
    - libstatiskit
    - python-toolchain
    - python-statiskit
  run:
    - python
    - statiskit-{{ environ.get('CONDA_FEATURE', 'stable') }}
    - {{ pin_compatible('devops-tools', exact=True) }}
    - {{ pin_compatible('vcs', exact=True) }}
    - {{ pin_compatible('statiskit-tools', exact=True) }}
    - {{ pin_compatible('libtoolchain-dev', exact=True) }}
    - {{ pin_compatible('libstatiskit-dev', exact=True) }}
    - {{ pin_compatible('libtoolchain', exact=True) }}
    - {{ pin_compatible('libstatiskit', exact=True) }}
    - {{ pin_compatible('python-toolchain', exact=True) }}
    - {{ pin_compatible('python-statiskit', exact=True) }}
    - matplotlib
    - ipython
    - jupyter