package:
  name: scons-tools
  version: "1.0.0"

source:
  path: .

build:
  number: 0

requirements:
  build:
    - python
  run:
    - python
    - python-scons
    - path.py
    - six
    - pyyaml

about:
  home: http://statiskit.rtfd.io/
  license: Apache License 2.0
  summary: SCons Tools for the StatisKit Software Suite

test:
  files:
    - SConstruct
  commands:
    - echo $SCONSFLAGS  [not win]
    - echo %SCONSFLAGS% [win]
    - scons -h
    - scons

