package:
    name: libstatiskit-dev
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    features:
        - {{ environ.get('CONDA_FEATURE', 'stable') }}
    track_features:
        - {{ environ.get('CONDA_FEATURE', 'stable') }}

build:
    number: 0

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package containing the C++ declarations of the StatisKit software suite

requirements:
    build:
        - python
        - libstatiskit_stl-dev
        - libstatiskit_linalg-dev
        - libstatiskit_core-dev
        - libstatiskit_glm-dev
    run:
        - python
        - {{ pin_compatible('libstatiskit_stl-dev', exact=True) }}
        - {{ pin_compatible('libstatiskit_linalg-dev', exact=True) }}
        - {{ pin_compatible('libstatiskit_core-dev', exact=True) }}
        - {{ pin_compatible('libstatiskit_glm-dev', exact=True) }}