package:
    name: python-pkg
    version: "1.0.0"

source:
    path: ../..

build:
    number: 0
    preserve_egg_dir: True
  
about:
    home: http://statiskit.readthedocs.org
    license: CeCILL

requirements:
    build:
        - python
        - pyyaml
    run:
        - python
        - pyyaml
        - gitpython
        # - github3.py
        - path.py
        - python-parse
        - mako