package:
  name: binutils
  version: 2.25
  
build:
  number: 3
  detect_binary_files_with_prefix: True

requirements:
  build:
    - system # [not win]
    #- gcc 4.8.2

source:
  fn: binutils-2.25.tar.bz2
  url: http://ftp.gnu.org/gnu/binutils/binutils-2.25.tar.bz2
