package:
  name: python-scons
  version: "2.5.0"

source:
  fn: scons-2.5.0.tar.gz
  url: https://sourceforge.net/projects/scons/files/scons/2.5.0/scons-2.5.0.tar.gz

build:
  number: 0

requirements:
  build:
    - python
    - pyyaml
    - path.py
  run:
    - python
    - pyyaml
    - path.py
test:
  files:
    - SConstruct
  commands:
    - scons $SCONSFLAGS     [not win]
    - scons                 [not win]

about:
  home: http://www.scons.org/
  license: MIT
  summary: 'Open Source next-generation build tool.'
