package:
  name: python-pkgtk
  version: "1.0.0"

source:
  path: ../..

build:
  number: 0
  script: python setup.py install

about:
  home: http://pkgtk.readthedocs.org
  license: CeCILL-C

requirements:
  build:
    - python
  run:
    - python

test:
   requires:
     - nose
     - coverage
   commands:
     - cd {{ SRC_DIR }} 
     - nosetests -v --pdb --with-coverage --cover-package=pkgtk
