package:
  name: mpc
  version: 1.0.3

source:
  url: http://www.multiprecision.org/mpc/download/mpc-1.0.3.tar.gz
  fn: mpc-1.0.3.tar.gz

build:
  detect_binary_files_with_prefix: True
  number: 2
  
requirements:
  build:
    - gmp >=6.1.0
    - mpfr >=3.1.4
  run:
    - gmp >=6.1.0
    - mpfr >=3.1.4

about:
  home: http://www.multiprecision.org/
  license: GPL
  summary: Gnu Mpc is a C library for the arithmetic of complex numbers with arbitrarily high precision and correct rounding of the result.
