package:
  name: statiskit-tools
  version: "1.0.0"

source:
    path: ../../..

build:
    number: 0
    entry_points:
        - build_system = statiskit.tools.cli:main_build_system
    preserve_egg_dir: False

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: Tools for unifying software development and operation with the StatisKit organization

requirements:
  build:
    - python
    - devops-tools
  run:
    - python
    - devops-tools

test:
    source_files:
        - '*'
        - '.*'
    requires:
        - python-toolchain
    commands:
        - build_system --help