package:
  name: vcs
  version: "1.0.0"
    
build:
  number: 0
  always_include_files:
    - etc/gitconfig

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL

requirements:
  build:
    - git
  run:
    - git