package:
  name: python-statiskit
  version: 1.0.0

build:
  number: 0

about:
  home: http://statiskit.rtfd.io/
  license: Apache License 2.0
  summary: The Python API of the StatisKit software suite.
  
requirements:
  build:
    - python
  run:
    - python
    - python-statiskit_stl
    - python-statiskit_linalg
    - python-statiskit_core