package:
    name: python-statiskit
    version: {{ environ.get('GIT_DESCRIBE_TAG', '0.9.0') }}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  features:
    - {{ environ.get('CONDA_FEATURE', 'stable') }}
  track_features:
    - {{ environ.get('CONDA_FEATURE', 'stable') }}

about:
    home: http://statiskit.readthedocs.io/
    license: Apache License 2.0
    summary: A meta-package containing the python interface to the StatisKit software suite

requirements:
  build:
    - python
    - python-statiskit_stl
    - python-statiskit_linalg
    - python-statiskit_core
    - python-statiskit_glm
  run:
    - python
    - {{ pin_compatible('python-statiskit_stl', exact=True) }}
    - {{ pin_compatible('python-statiskit_linalg', exact=True) }}
    - {{ pin_compatible('python-statiskit_core', exact=True) }}
    - {{ pin_compatible('python-statiskit_glm', exact=True) }}