package:
  name: zlib
  version: 1.2.8

source:
  fn: zlib-1.2.8.tar.gz
  url: http://zlib.net/zlib-1.2.8.tar.gz

build:
  number: 0
  script_env:
    - TOOLCHAIN # [not win]
  features:
    - {{ TOOLCHAIN }} # [not win]
  track_features:
    - {{ TOOLCHAIN }} # [not win]

requirements:
  build:
    - toolchain

about:
  home: http://zlib.net/
  license: zlib (http://zlib.net/zlib_license.html)
  summary: "A Massively Spiffy Yet Delicately Unobtrusive Compression Library"
