package:
  name: libdev
  version: "1.0.0"
    
build:
  number: 0
  track_features:
    # - vc9                 [win and py27]
    # - vc10                [win and py34]
    # - vc14                [win and py35]
    - vc14                 [win]

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL
  
requirements:
  build:
    - python 2.7
    - python-scons
    - pywin32             [win]
    # - vs2008_runtime      [win and py27]
    # - vs2010_runtime      [win and py34]
    # - vs2015_runtime      [win and py35]
    - vs2015_runtime      [win]
  run:
    - python 2.7
    - python-scons
    - pywin32             [win]
    # - vs2008_runtime      [win and py27]
    # - vs2010_runtime      [win and py34]
    # - vs2015_runtime      [win and py35]
    - vs2015_runtime      [win]
