package:
  name: python-doc
  version: "1.0.0"
    
build:
  number: 1

about:
  home: http://statiskit.readthedocs.io
  license: CeCILL

requirements:
  build:
    - python
    - sphinx
    - cmake
    - pillow
  run:
    - python
    - sphinx
    - pillow
