
# Adpated from https://github.com/conda/conda-recipes/tree/master/boost
package:
  name: toolchain
  version: 0.9.0

build:
  number: 0

about:
  home: http://statiskit.rtfd.io/
  license: CeCILL-C

requirements:
  build:
    - python
    - mingw 4.7 # [win]
  run:
    - python
    - mingw 4.7 # [win]

test:
  commands:
    - echo $TOOLCHAIN # [unix]
    - echo %TOOLCHAIN% # [win]