
# Adpated from https://github.com/conda/conda-recipes/tree/master/boost
package:
  name: toolchain
  version: 0.9.0

build:
  number: 0

about:
  home: http://statiskit.rtfd.io/
  license: CeCILL-C

requirements:
  build:
    - python
    - mingwpy # [win and x86_64]
    - mingw # [win and x86]
  run:
    - python
    - mingwpy # [win and x86_64]
    - mingw # [win and x86]

test:
  commands:
    - echo $TOOLCHAIN # [unix]
    - gcc -dumpversion # [win]
    - g++ -dumpversion # [win]
